### ISSUE TITLE
About qt ui interaction.

### ISSUE THREAD

**Issue by jonike** [bergjones/Shadows_Spider#25]
I noticed that Shadow's Spider 1.0 demonstrated in the youtube video. It's implemented the qt interaction. I do not know how to implement the right menu like maya, Could you show me a code example? Thank you.

video link: https://www.youtube.com/watch?v=ll6h43GsIdM

**Comment by bergjones** [comment]
@jonike 

![capture](https://user-images.githubusercontent.com/11649418/30944540-949be8fc-a3c6-11e7-934c-683f233ce8de.JPG)

Are you talking about this or something else?

**Comment by jonike** [comment]
yes, like this sphere menu implement. it's cool.
thanks.

**Comment by bergjones** [comment]
@jonike 

You use the RadPop.cpp functions which stand for radial popup. Basically you find what and where your cursor is hovering over and use that as the origin to draw the 2D circle and line and refresh the various Attribute / shortcut / outliner tables. You must change the 

Does this answer your question?

**Comment by jonike** [comment]
Ok,I see, I will try it. Thank you for your promptly reply.
